database:
  login: login
  password: password
  tns: tns
soap:
  wsdl: ../zppm_projc_upload_17092014_in.wsdl
  proxy: http://user:password@proxy.address:8080/
  login: login
  password: password
intgration:
  start_year: 2014
  start_time: 2013-01-01T00:00:00.0Z
