database:
  login: login
  password: password
  tns: tns
soap:
  proxy: http://user:password@proxy.address:8080/
  lot:
    wsdl: confic/lot.wsdl
    login: login
    password: password
  project:
    wsdl: config/project.wsdl
    login: login
    password: password
    system: '07'
intgration:
  lot:
    start_year: 2014
    start_time: 2013-01-01T00:00:00.0Z
    commission_types: [28004, 28005]
    plan_statuses: [15003, 15004, 15006, 15007]
  project:
    start_date: 2000-01-01
