tables:
  directions:
    aqua_name: varchar2(10)
    ksazd_id: number(38)
    ksazd_name: varchar2(100)
  commission_types:
    aqua_id: varchar2(10)
    aqua_name: varchar2(100)
    ksazd_id: number(38)
    ksazd_name: varchar2(100)
  departments:
    aqua_id: number(38)
    aqua_name: varchar2(100)
    ksazd_id: number(38)
    ksazd_name: varchar2(100)
  organizers:
    aqua_id: varchar2(10)
    aqua_department: varchar2(10)
    aqua_name: varchar2(100)
    ksazd_id: number(38)
    ksazd_name: varchar2(100)
  tender_types:
    aqua_id: varchar2(10)
    aqua_id2: varchar2(10)
    aqua_name: varchar2(200)
    ksazd_id: number(38)
    ksazd_short_name: varchar2(10)
    ksazd_full_name: varchar2(200)
  cost_documents:
    aqua_id: number(38)
    aqua_name: varchar2(200)
    ksazd_name: varchar2(200)
  etp_addresses:
    aqua_id: char(1)
    ksazd_id: number(38)
    ksazd_name: varchar2(100)
  monitor_services:
    aqua_id: number(38)
    aqua_name: varchar2(200)
    ksazd_id: number(38)
    ksazd_name: varchar2(200)
  subdirections:
    aqua_name: varchar2(20)
    ksazd_direction_id: number(38)
    ksazd_subject_type_id: number(38)
    aqua_description: varchar2(200)
  project_departments:
    aqua_id: number(38)
    aqua_name: varchar2(100)
    ksazd_id: number(38)
    ksazd_name: varchar2(100)
  app_variables:
    key: varchar2(100)
    value: varchar2(100)
  aqua_lots:
    id: number(38)
    plan_spec_guid: raw(16)
    spec_guid: raw(16)
    state: char(1)
  deliveries:
    aqua_lot_id: number(38)
    state: char(1)
    attempted_at: date
    message: varchar2(1000)
sequences:
  - aqua_lots_seq
